spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: cc.blynk.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://10.168.0.23:8123/default
    username: default
    password:


mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8090
