package com.example.backend.dao;

import com.example.backend.po.CountItem;
import com.example.backend.po.Logmanagementsystem;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface LogmanagementsystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logManagementSystem
     *
     * @mbg.generated Tue Jan 10 10:53:47 CST 2023
     */
    int insert(Logmanagementsystem record);

    List<Logmanagementsystem> selectAll();

    Logmanagementsystem selectTest();

    List<String> getEnumContainerName();

    List<String> getEnumContainerId();

    List<String> getEnumLevel();

    List<String> getEnumAppName();

    List<String> getEnumSource();

    List<String> getEnumClass();

    Long getMinTimestamp();

    Long getMaxTimestamp();

    List<CountItem> getCountTotalByAppName();

    List<CountItem> getCountTotalByContainerId();

    List<CountItem> getCountTotalByContainerName();

    List<CountItem> getCountTotalByLevel();

    List<CountItem> getCountLevelByAppName(@Param("appname") String appName);

    List<CountItem> getCountLevelByContainerId(@Param("containerid") String containerId);

    List<CountItem> getCountLevelByContainerName(@Param("containername") String containerName);

    List<Logmanagementsystem> selectRange(@Param("start") Long start, @Param("end") Long end);

    List<Logmanagementsystem> selectRangeByAppName(@Param("start") Long start, @Param("end") Long end,
                                                   @Param("appname") String appName);

    List<Logmanagementsystem> selectRangeByContainerId(@Param("start") Long start, @Param("end") Long end,
                                                       @Param("containerid") String containerId);

    List<Logmanagementsystem> selectRangeByContainerName(@Param("start") Long start, @Param("end") Long end,
                                                         @Param("containername") String containerName);

    Integer selectRangeCount(@Param("start") Long start, @Param("end") Long end);
    Integer selectRangeByAppNameCount(@Param("start") Long start, @Param("end") Long end,
                                                   @Param("appname") String appName);
    Integer selectRangeByContainerIdCount(@Param("start") Long start, @Param("end") Long end,
                                                       @Param("containerid") String containerId);
    Integer selectRangeByContainerNameCount(@Param("start") Long start, @Param("end") Long end,
                                                         @Param("containername") String containerName);

    Logmanagementsystem selectByUuid(@Param("uuid") String uuid);
}