spring:
  application:
    name: eureka-server

logging:
  config: classpath:logback-logstash.xml

---
spring:
  profiles: eureka-server1
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8761


---
spring:
  profiles: eureka-server2
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8762